dist: bionic
language: node_js
node_js: 12

services:
  - docker

before_install:
  - if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then
      export NODE_TAG=master;
      export COMPILER_TAG=latest;
      export FORCE_COMPATIBILITY=true;
    fi
  - docker-compose up -d

install: npm ci --ignore-scripts

jobs:
  include:
    - stage: Tests
      name: Test AENS
      script:
        - npm run test:integration:aens
        - npm run report-coverage
    - name: Test Channel
      script:
        - npm run test:integration:channel
        - npm run report-coverage
    - name: Test Contract, Node, Oracle, Account and else
      script:
        - npm run lint
        - npm run build
        - npm run test:unit
        - npm run report-coverage
        - npm run test:integration:else
        - npm run report-coverage
